### ISSUE TITLE
Program hangs when displaying image with `use_kitty: true`

### ISSUE THREAD

**Issue by lilithium-hydride** [atanunq/viuer#30]
When setting the `use_kitty:` config option for viuer to `true` and attempting to display an image, the program will hang (seemingly indefinitely) and must be forcibly killed. No image is displayed. Setting this option to `false` allows everything to work as expected, albeit with blocks instead of a proper Kitty image. This is almost certainly a bug in my program, although I can't imagine what would cause such behavior and if anyone has any ideas I'd appreciate it :D

**Comment by atanunq** [comment]
Hello! What environment are you running in? Is it in Kitty? Also, is it in a tty?

Kitty has two levels of operation - local (by sending a file name) & remote (by sending the whole image encoded in terminal sequences). The first one is faster, but the logic to detect that is [here](https://github.com/atanunq/viuer/blob/133bb99fe7c6cf929ebe9a2e25ca243f620c2eaf/src/printer/kitty.rs#L79-L110). It is basically asking the terminal whether it can successfully print an image using the first method. However, I suspect in your case it is waiting for a response indefinitely. This usually happens if you are piping the output of `viuer` somewhere else, e.g `| head`.

This should be fixed on `viuer`'s side, to be honest.

**Comment by fort-ified** [comment]
I'm in x11, it's with Kitty, and it's not being piped anywhere. Running it in another terminal (I tried urxvt) does not cause it to hang. My guess is that, similarly to my previous issue, it's in raw mode and Kitty probably doesn't send the response that viuer expects.

**Comment by lilithium-hydride** [comment]
Doesn't seem to be much in the way of development here anymore, but it's worth mentioning that this seems to have resolved itself since I filed the issue. Closing.

**Comment by grubeli** [comment]
I have same issue now
`kitty 0.24.2`

**Comment by songww** [comment]
I have same issue
kitty 0.26.5

It stopped working after a dozen images were displayed.

**Comment by adri326** [comment]
Exact same issue, stops working after ~30 images
