### ISSUE TITLE
How to load image from bytes (include_bytes)?

### ISSUE THREAD

**Issue by KonradLinkowski** [atanunq/viuer#9]
I want to bundle my images with executable.
This is the code I used and it fails compilation with error
```
expected enum `image::dynimage::DynamicImage`, found array `[u8; 23307]
```
```
use viuer::{Config, print_from_file, print};
let conf = Config {
  transparent: true,
  absolute_offset: false,
  ..Default::default()
};
let img = include_bytes!("image.png");
print(img, &conf);
```
How could I convert bytes to `DynamicImage`?

**Comment by atanunq** [comment]
Hi,
It seems that you are not using the `print_from_file` function, although it is imported. It will help you with printing, all it needs is a path, see its signature [here](https://docs.rs/viuer/0.2.0/viuer/fn.print_from_file.html). You don't need to use `include_bytes!` in that case.

If you really want to load the image, you can have a look at the [image](https://docs.rs/image) library. It lets you do all kinds of manipulations to an image, including access to the raw data behind it. `viuer` uses it, and that's why the `viuer::print` method takes as an argument a `DynamicImage`.

**Comment by KonradLinkowski** [comment]
@atanunq thanks for the respons. `print_from_file` works fine, but I'm looking for the way to bundle the image with my executable.

**Comment by atanunq** [comment]
Oh, I see.
I am afraid `viuer` cannot help you with that. You should have a look at `image` functionality to load the image as a usable representation. If this should happen at compile time, I guess you could do this in a macro expansion of some sorts.
Also, I noticed there is a crate that does the magic for you - [`rust-embed`](https://github.com/pyros2097/rust-embed).

Closing, as this project does not aim to achieve this functionality.
